### PR TITLE
Fix the reversible implementation to get correct gradients.

### PR DESCRIPTION
**Pull request by GiggleLiu**

### CODE REVIEW

**Comment by refraction-ray** [comment]
@GiggleLiu , Aha, sounds a very interesting idea to differentia the backtest Sharpe ratio in terms of adjustable parameters in the policy. Is there any specific gain to utilize Ni here instead of conventional AD infrastructure?

**Comment by GiggleLiu** [comment]
Good question,
1) the practical concern
It is much faster than most AD packages, yet very memory efficient. See our paper:
https://arxiv.org/pdf/2003.04617.pdf
and 
https://github.com/JuliaReverse/NiBundleAdjustment.jl

2) reversible computing for future
Reversible computing is energy efficient by Landauer's principle. In the future, it can be compiled to energy efficient devices.
FYI: https://arxiv.org/pdf/1803.02789.pdf

**Comment by GiggleLiu** [comment]
Other advantages:

* This is maybe the only AD package that supports mutable arrays! (i.e. inplace operations)
* This is maybe the only AD package that supports differentiating GPU kernels using source code transformation.

In this case, Zygote fails because your program contains inplace operations.

**Comment by refraction-ray** [comment]
It is interesting to see Ni plays a role in differentiating backtest policies (as I guess they may be more naturally expressed as inplace operations for arrays?). Not sure of the motivation of such a project (research/ or just some side project for fun?) But anyway, if you are interested in such fields and may want more finance data or something, I think I can offer some help.
Besides, another field that I can think of is option pricing. By auto differentiating the pricing of options, one can obtain all sorts of Greeks the industry cares.

**Comment by GiggleLiu** [comment]
> I guess they may be more naturally expressed as inplace operations for arrays?

I think so. Inplace operations are used extensively. In BLAS, all functions are implemented as inplace functions. Because memory allocation is expensive.

> the motivation of such a project,

For research. I am very optimistic about reversible computing (a field that dies for ~15 years), it is very very cool. So I tried to implement AD in the reversible programming framework.
I was writting it for fun, however it turns out to beat most AD packages in the market in performance. Its performance is comparable to the state-of-the-art AD packages Tapenade in C language (commercial, and is not open source). I will keep maintaining it for sure.

> But anyway, if you are interested in such fields and may want more finance data or something, I think I can offer some help.

Thanks very much, but I know little about finance and is fully occupied by another consulting job.
I am just curious in how Ni can be helpful in your project. Although I have used Ni extensively in other projects. You are the first user who are willing to get hands dirty and write a reversible program.
It is definitely not easy to use such a package, you don't have much references. So, I am more than happy to offer technical supports.

**Comment by refraction-ray** [comment]
I am not the author of this project, just happen to see your PR on this == And I thought you know the author :)

**Comment by GiggleLiu** [comment]
Oh, I should see your ID earlier. :laughing: 

*Github System Message:
Dear user @refraction-ray, if you do not upload your avatar immediately, we will delete your account.*

**Comment by refraction-ray** [comment]
I am somehow enjoying the default one by gravatar :joy:

**Comment by HanLi123** [comment]
Thanks very much! And I'm the author :)  The main point I pay attention to NiLang is that it can get the partial derivatives easily, which is very suitable for parameter tuning of quantitative strategies. At present,  the industry using genetic algorithm, which lacks of efficiency . If one can use gradient descent to adjust parameters, it is definitely a revolution.

**Pull request merged**
